name: Node.js CI

on: 
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20.x'

      - name: Install root dependencies
        run: npm ci

      - name: Install dependencies for operator
        run: npm ci
        working-directory: ./simple-block-agreement/operator

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test